### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by shree32** [braathen/qlik-auth#8]
seriously it has biggest performance issues every time...always lots of waiting time to logged in for multiple users...and there is no solution for multinodes environment for this proxy url

**Comment by braathen** [comment]
seriously?

a ticket request is instant, it's a HTTP POST call to an API endpoint, if you have performance issues then the problem is likewise somewhere else. If not, feel free to debug the code and report back where the performance issue occurs for you. This module was built as an example how to do a ticket request 3 years ago.

if you have configured your Virtual Proxie(s) properly with a Custom Authentication URL the module will get all necessary parameters automatically through the querystring. The module was designed to not need any hardcoded URL's, proxies or such, and works perfectly fine in a multi node environment.

**Comment by shree32** [comment]
exactly
not always ...only when it is in idle status ...it gets hanged
Session LDAP:  LDAP://ABC.ABC.DIR
Session DOMAIN:  @ABC and not going ahead
I mean it should be active status and not to hanged

**Comment by braathen** [comment]
I'm not sure what you mean, are you using the session part of the module? not tickets? I'm not sure what status that is in to be honest, if it was ever finished.

**Comment by shree32** [comment]
in short node.js is getting hanged

**Comment by braathen** [comment]
ok, I'm sorry but I'm afraid I cannot help you with that.
